import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Scene} from './Scene';import type {Telemetry} from './types';import './style.css';
const format=(v:number|undefined,d=2)=>v===undefined?'—':v.toFixed(d);
function App(){
 const [data,setData]=useState<Telemetry|null>(null),[connected,setConnected]=useState(false),[tab,setTab]=useState('Simulation'),[view,setView]=useState('Orbit'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[width,setWidth]=useState(.8),[height,setHeight]=useState(.6),[yaw,setYaw]=useState(0),[runs,setRuns]=useState<any[]>([]);
 const [history,setHistory]=useState<Telemetry[]>([]);const last=useRef(-1);
 useEffect(()=>{let socket:WebSocket;let timer:ReturnType<typeof setTimeout>;let stopped=false;const connect=()=>{socket=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws`);socket.onopen=()=>setConnected(true);socket.onmessage=e=>{const s=JSON.parse(e.data);setData(s);setConnected(s.connected!==false);if(s.position&&s.time!==last.current){const reset=s.time<last.current;setHistory(h=>reset?[s]:[...h,s].slice(-1000));last.current=s.time}};socket.onclose=()=>{setConnected(false);if(!stopped)timer=setTimeout(connect,1500)}};connect();return()=>{stopped=true;clearTimeout(timer);socket.close()}},[]);
 async function send(path:string,body:unknown){setBusy(true);setError('');try{const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok){const e=await r.json();throw new Error(typeof e.detail==='string'?e.detail:JSON.stringify(e.detail))}}catch(e){setError(String(e))}finally{setBusy(false)}}
 useEffect(()=>{if(tab==='Experiments')fetch('/api/results').then(r=>r.json()).then(setRuns).catch(e=>setError(String(e)))},[tab]);
 const idle=data?.state==='IDLE',terminal=['COMPLETE','ABORT','EMERGENCY_HOVER'].includes(data?.state||'');
 const velocity=data?.velocity?Math.hypot(...data.velocity):undefined;
 return <><header><div className="brand"><b>◈</b><span>ApertureNav<span className="muted"> / SIM</span><small>MATHTECH · ROBOTICS LAB</small></span></div><nav>{['Simulation','Scenarios','Analytics','Experiments'].map(t=><button className={tab===t?'active':''} key={t} onClick={()=>setTab(t)}>{t}</button>)}</nav><span className={connected?'online':'offline'}>● {connected?'CONNECTED':'DISCONNECTED'}</span></header>
 <main><div className="title"><div><span className="eyebrow">CONFINED SPACE NAVIGATION</span><h1>{tab==='Simulation'?'A clear path forward.':tab}</h1><p>{data?.source||'Connecting to simulation service…'}</p></div><div className="pill">{data?.state||'CONNECTING'}</div></div>
 {error&&<div className="error" role="alert">{error}<button onClick={()=>setError('')}>Dismiss</button></div>}
 {tab==='Simulation'&&<><section className="workspace"><div className="viewport panel"><div className="panelbar"><span>01 / SPATIAL VIEW</span><div>{['Orbit','Top','Side','FPV'].map(v=><button className={view===v?'selected':''} key={v} onClick={()=>setView(v)}>{v}</button>)}</div></div><Scene data={data} view={view}/><div className="viewportfoot"><span>── Flight trail <i>┄┄ Planned corridor</i></span><span>World frame · metres</span></div></div><aside><section className="panel telemetry"><div className="panelbar">02 / LIVE TELEMETRY</div><div className="metric large"><span>Minimum clearance</span><strong className={data?.safe?'good':'warn'}>{format(data?.clearance,3)} <small>m</small></strong><em>{data?.safe?'Clearance available':'Clearance not verified'}</em></div><div className="metrics">{[['Speed',format(velocity)+' m/s'],['Distance',format(data?.distance)+' m'],['Elapsed',format(data?.time,1)+' s'],['Collisions',data?.collisions??'—']].map(([l,v])=><div className="metric" key={l}><span>{l}</span><strong>{v}</strong></div>)}</div><div className="coordinates">{['X','Y','Z'].map((v,i)=><span key={v}>{v} <b>{format(data?.position?.[i])}</b></span>)}</div><div className="coordinates"><span>YAW <b>{format(data?.yaw!==undefined?data.yaw*180/Math.PI:undefined,1)}°</b></span><span>MODE <b>AUTONOMOUS</b></span></div></section><section className="panel events"><div className="panelbar">03 / MISSION EVENTS</div>{data?.events?.slice(-5).reverse().map((e,i)=><div className="event" key={`${e.timestamp}-${i}`}><time>{e.timestamp.toFixed(1)}s</time><div><b>{e.to.replaceAll('_',' ')}</b><p>{e.reason}</p></div></div>)}{!data?.events?.length&&<p className="empty">Start a mission to record transitions.</p>}</section></aside></section><section className="panel controls"><div><b>Mission control</b><p>{data?.paused?'Simulation paused':'Ready for your next experiment'}</p></div><div className="buttons"><button className="primary" disabled={!connected||!idle||busy} onClick={()=>send('/api/command',{action:'start'})}>▶ Start mission</button><button disabled={!connected||idle||terminal||busy} onClick={()=>send('/api/command',{action:data?.paused?'resume':'pause'})}>{data?.paused?'Resume':'Pause'}</button><button disabled={!connected||busy} onClick={()=>send('/api/command',{action:'reset'})}>↻ Reset</button><button disabled={!connected||idle||terminal||busy} onClick={()=>send('/api/command',{action:'abort'})}>Abort</button><button className="danger" disabled={!connected||terminal||busy} onClick={()=>send('/api/command',{action:'estop'})}>■ Emergency stop</button></div></section></>}
 {tab==='Scenarios'&&<section className="panel form"><h2>Opening geometry</h2><p>Reset the mission before applying a scenario. Parameters below control the local kinematic simulator; ROS uses its launch configuration.</p><div className="presets">{[['Wide',1.2,.8],['Standard',.8,.6],['Tight',.6,.6],['Unsafe',.45,.4]].map(([l,w,h])=><button key={l} onClick={()=>{setWidth(Number(w));setHeight(Number(h))}}>{l}</button>)}</div>{[['Width (m)',width,setWidth,.3,2,.01],['Height (m)',height,setHeight,.25,2,.01],['Yaw (°)',yaw,setYaw,-45,45,1]].map(([label,value,setter,min,max,step])=><label key={String(label)}>{String(label)}<input type="number" value={Number(value)} min={Number(min)} max={Number(max)} step={Number(step)} onChange={e=>(setter as (n:number)=>void)(Number(e.target.value))}/></label>)}<button className="primary" disabled={!idle||busy||!connected} onClick={()=>send('/api/scenario',{width,height,yaw_degrees:yaw,seed:42})}>Apply scenario</button></section>}
 {tab==='Analytics'&&<section className="charts">{[['Clearance (m)',(r:Telemetry)=>r.clearance],['Speed (m/s)',(r:Telemetry)=>Math.hypot(...r.velocity)],['Distance (m)',(r:Telemetry)=>r.distance],['Altitude (m)',(r:Telemetry)=>r.position[2]]].map(([label,fn])=><Chart key={String(label)} title={String(label)} values={history.map(fn as (r:Telemetry)=>number)}/>)}<div className="panel note">Charts show the latest 1,000 live samples. Full telemetry is saved with each completed or stopped experiment.</div></section>}
 {tab==='Experiments'&&<section className="panel results"><h2>Recorded runs</h2><p>Download actual results generated by this installation.</p><table><thead><tr><th>Run</th><th>State</th><th>Duration</th><th>Path</th><th>Data</th></tr></thead><tbody>{runs.map(r=><tr key={r.id}><td>{r.id}</td><td>{r.state}</td><td>{format(r.mission_duration)} s</td><td>{format(r.path_length)} m</td><td><a href={`/api/results/${r.id}/telemetry.csv`}>CSV</a> · <a href={`/api/results/${r.id}/summary.json`}>JSON</a></td></tr>)}</tbody></table>{!runs.length&&<p className="empty">No recorded runs yet.</p>}</section>}
 </main><footer><span>ApertureNav-Sim 0.1 · Research baseline</span><span>SIMULATION ONLY · RECTANGULAR APERTURES</span></footer></>;
}
function Chart({title,values}:{title:string;values:number[]}){const min=Math.min(0,...values),max=Math.max(.1,...values),range=max-min;const points=values.map((v,i)=>`${20+i*560/Math.max(1,values.length-1)},${160-(v-min)*130/range}`).join(' ');return <section className="panel chart"><h2>{title}</h2><svg viewBox="0 0 600 190" role="img" aria-label={title}><path d="M20 20 V160 H580" stroke="#38495d" fill="none"/><polyline points={points} stroke="#54e8c1" fill="none" strokeWidth="2"/><text x="24" y="16">{max.toFixed(2)}</text><text x="24" y="180">{min.toFixed(2)} · time →</text></svg></section>}
createRoot(document.getElementById('root')!).render(<App/>);
